### PR TITLE
add multi arrow and reset

### PR DESCRIPTION
**Pull request by joshrule**
just a couple helper functions (and a cleaner history).

### CODE REVIEW

**Comment by lucasem** [comment]
The `multi_arrow` feature actually already exists via `impl<N: Name> From<Vec<Type<N>> for Type<N>` (and `VecDeque` as well) — so you can use `Type::from(vec![tp_a, tp_b, tp_c])` (it would ideally be `TryFrom` but that isn't stable yet. Because it's already in there, I'm not sure whether or not it should be added via this method. What do you think?

**Comment by joshrule** [comment]
Oh, cool - I had no idea, but I really like that! I can remove `multi_arrow` tomorrow and add a couple sentences mentioning the `From` `impls` more prominently in the documentation for `Type`?

**Comment by lucasem** [comment]
Yeah that sounds good to me!

**Comment by joshrule** [comment]
Oh, let me rebase this onto what you've pushed in the last few hours.

**Pull request closed without merging**
